// <auto-generated />
using System;
using DescagaCompronanteSRI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SriCrawler.Core.Persistence.Migrations
{
    [DbContext(typeof(CrawlerDbContext))]
    [Migration("20261008014512_DocumentValidationAndMetadata")]
    partial class DocumentValidationAndMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crawler")
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.DocumentConversion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("DocumentJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ParserName")
                        .HasColumnType("text");

                    b.Property<string>("ParserVersion")
                        .HasColumnType("text");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("XmlHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "XmlHash", "ParserVersion");

                    b.ToTable("conversions", "crawler");
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.DocumentFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<string>("LocalPath")
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .HasColumnType("text");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ValidationJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month");

                    b.HasIndex("DocumentId", "Format", "Year", "Month")
                        .IsUnique();

                    b.ToTable("files", "crawler");
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.DocumentRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessKey")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("IssuerTaxpayerId")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("TaxpayerId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "TaxpayerId", "Direction", "DocumentType", "AccessKey")
                        .IsUnique();

                    b.ToTable("documents", "crawler");
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.ExtractionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<Guid>("ExtractionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionId", "Number")
                        .IsUnique();

                    b.ToTable("attempts", "crawler");
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.ExtractionDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ConversionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<int>("DownloadStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExtractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileHash")
                        .HasColumnType("text");

                    b.Property<long?>("FileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("IssuedDate")
                        .HasColumnType("date");

                    b.Property<int>("JsonStatus")
                        .HasColumnType("integer");

                    b.Property<int>("MetadataParseStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SeenAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceValuesJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("StorageStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Taxes")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("ValidationJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConversionId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FileId");

                    b.HasIndex("ExtractionId", "Identity")
                        .IsUnique();

                    b.ToTable("results", "crawler");
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.ExtractionFailure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ExtractionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionId", "Id");

                    b.ToTable("failures", "crawler");
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.ExtractionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExtractionStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JobStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaginationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("QueryJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("QuerySucceeded")
                        .HasColumnType("boolean");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaxpayerId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "TaxpayerId", "CreatedAt");

                    b.ToTable("extractions", "crawler");
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.JobDispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExtractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionId")
                        .IsUnique();

                    b.ToTable("dispatches", "crawler");
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.DocumentConversion", b =>
                {
                    b.HasOne("DescagaCompronanteSRI.Persistence.DocumentRecord", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.DocumentFile", b =>
                {
                    b.HasOne("DescagaCompronanteSRI.Persistence.DocumentRecord", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.ExtractionAttempt", b =>
                {
                    b.HasOne("DescagaCompronanteSRI.Persistence.ExtractionRecord", null)
                        .WithMany()
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.ExtractionDocument", b =>
                {
                    b.HasOne("DescagaCompronanteSRI.Persistence.DocumentConversion", null)
                        .WithMany()
                        .HasForeignKey("ConversionId");

                    b.HasOne("DescagaCompronanteSRI.Persistence.DocumentRecord", null)
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.HasOne("DescagaCompronanteSRI.Persistence.ExtractionRecord", null)
                        .WithMany()
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DescagaCompronanteSRI.Persistence.DocumentFile", null)
                        .WithMany()
                        .HasForeignKey("FileId");
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.ExtractionFailure", b =>
                {
                    b.HasOne("DescagaCompronanteSRI.Persistence.ExtractionRecord", null)
                        .WithMany()
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DescagaCompronanteSRI.Persistence.JobDispatch", b =>
                {
                    b.HasOne("DescagaCompronanteSRI.Persistence.ExtractionRecord", null)
                        .WithMany()
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
