@HostAddress = http://localhost:5276
@SriUser = TU_RUC
@SriPassword = TU_PASSWORD_SRI
@SriAccessKey = CLAVE_ACCESO_49_DIGITOS

### Query received documents (XML)
POST {{HostAddress}}/api/received-documents/query
Content-Type: application/json

{
  "user": "{{SriUser}}",
  "additionalUser": null,
  "password": "{{SriPassword}}",
  "year": 2026,
  "month": 6,
  "day": 0,
  "documentType": "invoice",
  "downloadFormat": "xml"
}

### Query received documents (PDF)
POST {{HostAddress}}/api/received-documents/query
Content-Type: application/json

{
  "user": "{{SriUser}}",
  "additionalUser": null,
  "password": "{{SriPassword}}",
  "year": 2026,
  "month": 6,
  "day": 0,
  "documentType": "invoice",
  "downloadFormat": "pdf"
}

### Consultar comprobantes emitidos (PDF)
POST {{HostAddress}}/api/SriEmitidos/consultar
accept: */*
Content-Type: application/json

{
  "usuario": "{{SriUser}}",
  "usuarioAdicional": "",
  "password": "{{SriPassword}}",
  "comprobante": 1,
  "anio": 2026,
  "mes": 6,
  "dia": 25
}

### Descargar PDF emitido guardado
GET {{HostAddress}}/api/SriEmitidos/descargar/{{SriUser}}/{{SriAccessKey}}
accept: application/pdf
